version: '3.8'

services:
  # =========================================
  # 1. Go åº”ç”¨ (Web3 Monitor)
  # =========================================
  flash-monitor:
    image: flash-monitor:v1
    container_name: flash_monitor_app
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      # è¯·æ ¹æ®ä½ å®é™…çš„ VPN ç«¯å£ä¿®æ”¹ 
      - HTTP_PROXY=http://host.docker.internal:19828
      - HTTPS_PROXY=http://host.docker.internal:19828
    volumes:
      # ğŸ‘‡ å…³é”®ï¼šå› ä¸º docker-compose.yml åœ¨çˆ¶ç›®å½•ï¼Œä»£ç åœ¨å­ç›®å½•ï¼Œæ‰€ä»¥è·¯å¾„è¦åŠ å­ç›®å½•å
        - ./configs/config.docker.yaml:/app/configs/config.yaml
        - ./logs:/app/logs
    networks:
      - flash_net

  # =========================================
  # 2. MySQL 
  # =========================================
  mysql:
    image: mysql:8.0
    container_name: flash_monitor_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "flash_monitor"
      MYSQL_USER: "ZY"
      MYSQL_PASSWORD: "123456"
    ports:
      - "53307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
      - flash_net

  # =========================================
  # 3. Redis (åŸºç¡€è®¾æ–½)
  # =========================================
  redis:
    image: redis:alpine
    container_name: flash_monitor_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - flash_net

  # =========================================
  # 4. Adminer (åŸºç¡€è®¾æ–½)
  # =========================================
  adminer:
    image: adminer
    container_name: flash_monitor_adminer
    restart: always
    ports:
      - "59080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - flash_net

volumes:
  mysql_data:
  redis_data:

networks:
  flash_net:
    driver: bridge