app:
  env: "prod"            # ç”Ÿäº§ç¯å¢ƒæ¨¡å¼
  name: "flash-monitor"

chain:
  # ä¿æŒä¸å˜
  rpc_url: "https://ethereum-rpc.publicnode.com"
  contract_address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"

database:
  # ğŸ‘‡ é‡ç‚¹åœ¨è¿™é‡Œï¼šhost å˜æˆäº† "mysql"ï¼Œç«¯å£å˜æˆäº† "3306"
  dsn: "root:123456@tcp(mysql:3306)/flash_monitor?charset=utf8mb4&parseTime=True&loc=Local"